server:
  port: 8092
  servlet:
    context-path: /productService/
    
spring:
  main:
    banner-mode: "off"
  profiles:
    active:  default # default : to run application.yml file    &&  prod : to run application-prod.yml file
  jpa:
#    database: mysql
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
#   type: org.apache.tomcat.jdbc.pool.DataSource
    platform: postgres
    url: postgres://jzbnmevcksrrnk:617121ca965cb784a22ab4287d8a77b31e9c356cdc21750422c757d8fcabdf77@ec2-54-164-22-242.compute-1.amazonaws.com:5432/dbt6mg40v0rjk4
    username: jzbnmevcksrrnk
    password: 617121ca965cb784a22ab4287d8a77b31e9c356cdc21750422c757d8fcabdf77
    initialization-mode: always
#    data: classpath:sql-file/commonConfigData.sql
    tomcat:
      initial-size: 10
      max-wait: 300000
      max-active: 200
      max-idle: 30
      min-idle: 5
      timeBetweenEvictionRunsMillis: 120000
      minEvictableIdleTimeMillis: 600000
      removeAbandoned: true
      removeAbandonedTimeout: 60



